const QUESTIONS = {
  1: "Mikä saa sinut tuntemaan itsesi eläväksi?",
  2: "Millainen haluaisit olla kymmenen vuoden päästä?",
  3: "Mikä on paras neuvo, jonka olet koskaan saanut?",
  4: "Mistä asiasta olet viimeksi muuttanut mielipidettäsi?",
  5: "Mikä lapsuusmuistosi on kirkkain?",
  6: "Millaista rakkautta haluat elämääsi?",
  7: "Mikä pelko estää sinua tällä hetkellä?",
  8: "Kenelle olet kiitollinen ja miksi?",
  9: "Mikä on suurin saavutuksesi tähän mennessä?",
  10: "Millainen on täydellinen päiväsi?",
  11: "Mitä haluaisit oppia tänä vuonna?",
  12: "Mikä asia sinussa on muuttunut viimeisen vuoden aikana?",
  13: "Milloin viimeksi teit jotain ensimmäistä kertaa?",
  14: "Mikä on tärkein arvosi?",
  15: "Keneltä haluaisit pyytää anteeksi?",
  16: "Mikä unelma tuntuu mahdottomalta?",
  17: "Millaisissa tilanteissa olet parhaimmillasi?",
  18: "Mitä sinulle merkitsee menestys?",
  19: "Mikä ominaisuutesi on vahvuutesi?",
  20: "Mistä luovut helposti ja mistä et?",
  21: "Millainen ympäristö saa sinut voimaan hyvin?",
  22: "Mikä musiikkikappale kuvaa tämänhetkistä elämääsi?",
  23: "Keneen olet viimeksi ihailevasti suhtautunut?",
  24: "Mikä tekee sinusta uniikin?",
  25: "Millaista ystävyyttä haluat vaalia?",
  26: "Mikä asia elämässäsi kaipaa muutosta?",
  27: "Milloin olet viimeksi nauranut kunnolla?",
  28: "Mitä haluat sanoa itsellesi viiden vuoden päästä?",
  29: "Mikä on suurin haaveesi?",
  30: "Mistä haluaisit päästää irti?",
  31: "Mikä sinussa on pysynyt samana lapsesta asti?",
  32: "Kenelle haluaisit soittaa juuri nyt?",
  33: "Mikä on tärkein opetuksesi rakkaudesta?",
  34: "Miten osoitat välittämistäsi?",
  35: "Keneltä kaipaat anteeksiantoa?",
  36: "Millainen ystävä olet?",
  37: "Mikä on suurin väärinymmärryksesi ihmissuhteissasi?",
  38: "Kenelle haluaisit sanoa 'rakastan sinua'?",
  39: "Mikä tekee suhteesta hyvän?",
  40: "Miten käsittelet konflikteja?",
  41: "Keneen luotat ehdoitta?",
  42: "Millaista tukea tarvitset muilta?",
  43: "Mikä on paras yhteinen muistosi jonkun kanssa?",
  44: "Miten haluat tulla muistetuksi?",
  45: "Kenelle olet tärkein?",
  46: "Mikä on viimeisin merkityksellinen keskustelusi?",
  47: "Miten voisit olla parempi kumppani?",
  48: "Mikä tekee ihmisestä kiinnostavan?",
  49: "Keneltä olet oppinut eniten elämästä?",
  50: "Millaista rakkautta annat itsellesi?",
  51: "Mikä on sinulle tärkeää perheessä?",
  52: "Miten haluat vaikuttaa muihin ihmisiin?",
  53: "Kenelle haluaisit kirjoittaa kirjeen?",
  54: "Mikä on suurin uhrauksesi jonkun puolesta?",
  55: "Miten hoidat ystävyyssuhteita?",
  56: "Mikä tekee sinusta hyvän kuuntelijan?",
  57: "Keneen haluaisit olla paremmin yhteydessä?",
  58: "Millaista yhteyttä kaipaat?",
  59: "Mikä on paras komplimentti, jonka olet saanut?",
  60: "Mikä virheesi on opettanut sinulle eniten?",
  61: "Mitä haluaisit osata täydellisesti?",
  62: "Mikä haastaa sinua positiivisesti?",
  63: "Millainen oppija olet?",
  64: "Mikä kirja on muuttanut ajatteluasi?",
  65: "Mistä aiheesta haluaisit tietää enemmän?",
  66: "Mikä on ollut tärkein oppituntisi tänä vuonna?",
  67: "Miten kehität itseäsi?",
  68: "Mikä taito olisi sinulle hyödyllinen?",
  69: "Keneltä haluaisit oppia?",
  70: "Mikä asia on sinulle vielä vaikeaa?",
  71: "Millainen haaste houkuttelee sinua?",
  72: "Mitä neuvoa antaisit nuoremmalle itsellesi?",
  73: "Mikä epäonnistumisesi on ollut siunaus?",
  74: "Miten suhtaudut virheisiin?",
  75: "Mikä motivoi sinua oppimaan?",
  76: "Millainen opettaja olet muille?",
  77: "Mikä taitosi on kehittynyt viime aikoina?",
  78: "Mitä haluat ymmärtää paremmin?",
  79: "Mikä on seuraava kehityshaasteesi?",
  80: "Miten käsittelet pettymyksiä?",
  81: "Mikä kokemus on kypsyttänyt sinua?",
  82: "Millainen kasvu tuntuu oikealta?",
  83: "Mistä haluaisit olla rohkeampi?",
  84: "Mikä uusi näkökulma on avannut silmiäsi?",
  85: "Miten otat vastaan palautetta?",
  86: "Mikä on paras oppisi vastoinkäymisistä?",
  87: "Millainen mentori tarvitsisit?",
  88: "Mikä kysymys askarruttaa sinua?",
  89: "Miten haluat kehittyä ihmisenä?",
  90: "Mikä tietosi on osoittautunut vääräksi?",
  91: "Mikä tekee sinut luovaksi?",
  92: "Milloin olet viimeksi luonut jotain?",
  93: "Mikä into on jäänyt toteuttamatta?",
  94: "Millainen taide koskettaa sinua?",
  95: "Mitä tekisit, jos epäonnistuminen olisi mahdotonta?",
  96: "Mikä harrastus tuo sinulle iloa?",
  97: "Millainen projekti innostaisi sinua?",
  98: "Mistä saat inspiraatiota?",
  99: "Mikä estää luovuuttasi?",
  100: "Millainen ympäristö herättää mielikuvituksesi?",
  101: "Mikä taitosi on aliarvostettu?",
  102: "Mitä haluaisit luoda maailmaan?",
  103: "Mikä intohimosi on vahvin?",
  104: "Millainen leikki oli lapsena lempiäsi?",
  105: "Miten ilmaiset itseäsi?",
  106: "Mikä tekee sinusta energisen?",
  107: "Millainen luova prosessi sopii sinulle?",
  108: "Mistä unelmoit hiljaisina hetkinä?",
  109: "Mikä projekti jäi kesken?",
  110: "Millainen musiikki herättää tunteesi?",
  111: "Mikä luova työ kiinnostaisi sinua?",
  112: "Miten voisit tuoda enemmän luovuutta arkeen?",
  113: "Mikä on erikoisin ideasi?",
  114: "Millainen taide haluaisit luoda?",
  115: "Mistä löydät flow-tilasi?",
  116: "Mikä intosi ansaitsisi enemmän aikaa?",
  117: "Millainen on luova tilasi?",
  118: "Mikä esto pitäisi murtaa?",
  119: "Mistä saat voimaa luoda?",
  120: "Mikä tekisi sinusta onnellisemman luojan?",
  121: "Miten kehosi voi tänään?",
  122: "Mikä liikunta tuo sinulle iloa?",
  123: "Millainen ruoka ravitsee sinua parhaiten?",
  124: "Miten palaudut stressistä?",
  125: "Mikä on tärkein huolehtimisesi tapa?",
  126: "Millainen uni tekee sinusta levänneen?",
  127: "Mikä luontoelämys on jäänyt mieleesi?",
  128: "Miten kuuntelet kehoasi?",
  129: "Mikä on paras tapasi rentoutua?",
  130: "Millainen liikunta haastaa sinua sopivasti?",
  131: "Mikä ruoka tuo sinulle lohtua?",
  132: "Miten hoidat terveyttäsi?",
  133: "Mikä on lempipaikkasi luonnossa?",
  134: "Millainen aamurituaali sopisi sinulle?",
  135: "Miten käsittelet kipua?",
  136: "Mikä tekee olosi virkeäksi?",
  137: "Millainen lepo on sinulle tärkeää?",
  138: "Miten kehosi on muuttunut?",
  139: "Mikä tekee sinut vahvaksi?",
  140: "Millainen kosketus on sinulle tärkeä?",
  141: "Miten voisit liikkua enemmän ilosta?",
  142: "Mikä rutiini parantaa hyvinvointiasi?",
  143: "Millainen yhteys kehollasi ja mielellä on?",
  144: "Mikä tekee sinut energiseksi?",
  145: "Miten hoidat itseäsi sairaana?",
  146: "Mikä ulkoilma-aktiviteetti ilahduttaa sinua?",
  147: "Millainen ravinto tukee jaksamistasi?",
  148: "Miten kehosi viestii sinulle?",
  149: "Mikä on sinulle pyhä hetki päivässä?",
  150: "Millainen kehosi on viisas?",
  151: "Miten haluat huolehtia itsestäsi paremmin?",
  152: "Mikä seikkailu kutsuisi sinua?",
  153: "Mihin haluaisit matkustaa?",
  154: "Mikä tekee sinusta vapaan?",
  155: "Millainen kesäpäivä on täydellinen?",
  156: "Mistä nautit kesällä eniten?",
  157: "Mikä spontaani teko houkuttelisi?",
  158: "Millainen matka muuttaisi sinua?",
  159: "Mikä on parasta vapaudessa?",
  160: "Mihin haluaisit hypätä päätä ensin?",
  161: "Millainen riski kannattaisi ottaa?",
  162: "Mikä paikka tuntuu kodilta?",
  163: "Mistä löydät rauhan?",
  164: "Millainen seikkailu pelottaa ja innostaa?",
  165: "Mikä vuodenaika kuvaa sinua parhaiten?",
  166: "Mihin haluaisit paeta juuri nyt?",
  167: "Mikä tekee hetkestä ikimuistoisen?",
  168: "Millainen matkakumppani olet?",
  169: "Mikä kulttuurielämys on koskettanut sinua?",
  170: "Mihin suuntaan haluaisit ajelehtia?",
  171: "Mikä on paras spontaani muistosi?",
  172: "Millainen vapaus on sinulle tärkeää?",
  173: "Mikä este estää seikkailua?",
  174: "Mihin haluaisit kuluttaa kesäsi?",
  175: "Mikä tekee sinusta rohkean?",
  176: "Millainen paikka inspiroi sinua?",
  177: "Mikä matka olisi unelmiesi matka?",
  178: "Miten voisit tuoda enemmän seikkailua arkeen?",
  179: "Mikä on parasta kesässä?",
  180: "Millainen vapaus tekisi sinusta onnellisen?",
  181: "Mihin suuntaan elämäsi voisi suunnata?",
  182: "Mikä teki sinut iloiseksi tänään?",
  183: "Mistä olet syvästi kiitollinen?",
  184: "Mikä pieni asia tuo sinulle iloa?",
  185: "Kuka ihminen kirkastaa päiväsi?",
  186: "Millainen hetki on täynnä iloa?",
  187: "Mistä nautit aivan sydämestäsi?",
  188: "Mikä on paras lahjasi, jonka olet saanut?",
  189: "Millainen yllätys ilahduttaa sinua?",
  190: "Mistä haluaisit kiittää elämää?",
  191: "Mikä saa sinut hymyilemään?",
  192: "Millainen hetki on täydellistä läsnäoloa?",
  193: "Mistä arjen asiasta nautit?",
  194: "Mikä maku tai tuoksu tuo muistoja?",
  195: "Kenelle haluaisit sanoa kiitos?",
  196: "Mikä tekee sinusta ylpeän?",
  197: "Millainen onni on sinulle tärkeää?",
  198: "Mistä yllätyit positiivisesti?",
  199: "Mikä on paras muistosi viime vuodelta?",
  200: "Millainen hetki täyttää sydämesi?",
  201: "Mistä haluaisit nauttia enemmän?",
  202: "Mikä tekee tavallisesta päivästä hyvän?",
  203: "Kenelle olet tuonut iloa?",
  204: "Mikä on sinulle ylellisyyttä?",
  205: "Millainen kiitollisuus lämmittää sinua?",
  206: "Mistä haluat pitää kiinni?",
  207: "Mikä tapa viettää aikaa on arvokasta?",
  208: "Millainen ilo on puhdasta?",
  209: "Mistä tiedät olevasi onnellinen?",
  210: "Mikä asia elämässäsi on lahja?",
  211: "Millainen hetki ansaitset tänään?",
  212: "Mistä haluaisit kiittää itseäsi?",
  213: "Mikä työssäsi on merkityksellistä?",
  214: "Millainen työ olisi unelmatyötäsi?",
  215: "Mikä taitosi on arvokkain?",
  216: "Miten haluat vaikuttaa työsi kautta?",
  217: "Mikä motivoi sinua työelämässä?",
  218: "Millainen kutsumus vetää sinua?",
  219: "Mikä työssäsi on haastavaa?",
  220: "Miten haluat kehittyä ammatissasi?",
  221: "Mikä tekee työpäivästä hyvän?",
  222: "Millainen työympäristö tukee sinua?",
  223: "Mikä projekti on ollut merkityksellisin?",
  224: "Miten tasapainotat työn ja muun elämän?",
  225: "Mikä on paras palautteesi työstä?",
  226: "Millainen johtaja olet tai haluaisit olla?",
  227: "Mikä haaste työssä kasvattaa sinua?",
  228: "Miten ilmaiset ammattitaitoasi?",
  229: "Mikä on unelmatyösi sisältö?",
  230: "Millainen työyhteisö sopii sinulle?",
  231: "Mikä on suurin saavutuksesi työssä?",
  232: "Miten käsittelet työstressiä?",
  233: "Mikä tekee sinusta hyvän työkaverin?",
  234: "Millainen työ tuntuu merkitykselliseltä?",
  235: "Mikä on tärkein oppisi työelämästä?",
  236: "Miten haluat vaikuttaa maailmaan työsi kautta?",
  237: "Mikä on seuraava ammatillinen tavoitteesi?",
  238: "Millainen balanssi työn ja vapaa-ajan välillä on oikea?",
  239: "Mikä innostaa sinua työssäsi?",
  240: "Miten haluat muistuttaa työsi jälkiä?",
  241: "Mikä tekee työstä tyydyttävää?",
  242: "Millainen ura olisi sinulle oikea?",
  243: "Mikä on tärkein arvosi työssä?",
  244: "Mistä olisi aika päästää irti?",
  245: "Mikä muutos pelottaa sinua?",
  246: "Millainen uusi alku houkuttelee?",
  247: "Mistä vanhasta tottumuksesta haluat luopua?",
  248: "Mikä muutos olisi sinulle hyödyksi?",
  249: "Miten käsittelet menetystä?",
  250: "Mistä uskomuksesta voisit luopua?",
  251: "Mikä elämäsi kausi on päättymässä?",
  252: "Millainen muutos tekisi sinusta vapaammaksi?",
  253: "Mistä suhteesta on aika jatkaa eteenpäin?",
  254: "Mikä on vaikein asia päästää irti?",
  255: "Millainen uusi versio itsestäsi haluaa syntyä?",
  256: "Mistä taakasta haluat vapautua?",
  257: "Mikä muutos on väistämätön?",
  258: "Miten voisit helpottaa muutosta?",
  259: "Mistä menneisyydestä pidät edelleen kiinni?",
  260: "Mikä pelko estää muutosta?",
  261: "Millainen loppu on myös alku?",
  262: "Mistä haluaisit anteeksi antaa itsellesi?",
  263: "Mikä tapa ajatella ei enää palvele sinua?",
  264: "Millainen muutos olisi rohkeaa?",
  265: "Mistä identiteetistäsi haluat luopua?",
  266: "Mikä suru kaipaa käsittelyä?",
  267: "Millainen siirtymävaihe olet nyt?",
  268: "Mistä on vaikea hyvästellä?",
  269: "Mikä muutos tuntuu oikealta?",
  270: "Miten voisit tukea itseäsi muutoksessa?",
  271: "Mistä vanhentuneesta unelmasta voit luopua?",
  272: "Mikä uusi mahdollisuus avautuu päästettäessä irti?",
  273: "Millainen muutos vapauttaisi energiaasi?",
  274: "Milloin viimeksi olit todella hiljaa?",
  275: "Mikä ajatus nousee hiljaisuudessa?",
  276: "Millainen sisäinen ääni ohjaa sinua?",
  277: "Mikä syvä kysymys askarruttaa sinua?",
  278: "Miten löydät rauhan sisältäsi?",
  279: "Mikä on tärkein totuutesi?",
  280: "Millainen hiljaisuus on arvokasta?",
  281: "Mistä syvästä asiasta haluaisit keskustella?",
  282: "Mikä on elämäsi suurin mysteeri?",
  283: "Miten kuuntelet itseäsi?",
  284: "Mikä tekee hetkestä pyhän?",
  285: "Millainen hiljaisuuden muoto on sinulle tärkeä?",
  286: "Mikä syvä pelko elää sisälläsi?",
  287: "Miten löydät ytimesi?",
  288: "Mikä on suurin filosofinen kysymyksesi?",
  289: "Millainen kontemplatiivinen käytäntö sopisi sinulle?",
  290: "Mistä löydät merkityksen?",
  291: "Mikä on elämäsi syvempi tarkoitus?",
  292: "Miten yksinolo vaikuttaa sinuun?",
  293: "Mikä on tärkein sisäinen viisautesi?",
  294: "Millainen hiljaisuus pelottaa sinua?",
  295: "Mistä arvoistasi et tingi?",
  296: "Mikä on syvimmän olemuksesi luonne?",
  297: "Miten meditaatio tai rauhoittuminen tukee sinua?",
  298: "Mikä kysymys johtaa aina syvemmälle?",
  299: "Millainen hiljaisuus parantaa?",
  300: "Mistä löydät henkisen kotisi?",
  301: "Mikä on syvällisintä kommunikaatiota?",
  302: "Miten luot tilaa sisäiselle äänellesi?",
  303: "Mikä totuus on vaikea kohdata?",
  304: "Millainen syvyys rikastuttaa elämääsi?",
  305: "Mikä on pimeydessäsi valoa?",
  306: "Miten käsittelet synkkiä aikoja?",
  307: "Mikä tuo sinulle toivoa?",
  308: "Millainen pimeys on osa sinua?",
  309: "Mistä löydät valon pimeimpinä hetkinä?",
  310: "Mikä puolesi kaipaa hyväksyntää?",
  311: "Miten hoidat masentuneisuutta?",
  312: "Mikä tekee sinusta resilientin?",
  313: "Millainen varjo sinulla on?",
  314: "Mistä ammennat voimaa vaikeina aikoina?",
  315: "Mikä on suurin pelkosi?",
  316: "Miten käsittelet ahdistusta?",
  317: "Mikä tuo sinulle lohtua?",
  318: "Millainen pimeys on luovaa?",
  319: "Mistä löydät rohkeutta?",
  320: "Mikä on sinulle turvasatama?",
  321: "Miten kohtaat kipusi?",
  322: "Mikä tekee sinusta rohkean?",
  323: "Millainen haavoittuvuus on voimaa?",
  324: "Mistä tiedät selviäväsi?",
  325: "Mikä on opettanut sinua kärsimys?",
  326: "Miten autat itseäsi pimeänä aikana?",
  327: "Mikä on toivon lähteesi?",
  328: "Millainen pimeys on hyväksyttävää?",
  329: "Mistä löydät sisäisen valosi?",
  330: "Mikä tekee sinusta sitkeän?",
  331: "Miten muistutat itseäsi omasta arvostasi?",
  332: "Mikä on suurin haasteesi tällä hetkellä?",
  333: "Millainen tuki auttaa sinua?",
  334: "Mistä tiedät, että huominen on parempi?",
  335: "Mistä olet kiitollinen tältä vuodelta?",
  336: "Mikä on suurin oppisi tänä vuonna?",
  337: "Millainen olet kasvanut?",
  338: "Mikä hetki on ollut merkityksellisin?",
  339: "Kenelle haluat kiittää tästä vuodesta?",
  340: "Mikä muutos on tapahtunut sinussa?",
  341: "Mistä olet ylpeä tältä vuodelta?",
  342: "Millainen haave toteutui?",
  343: "Mikä yllätys ilahdutti sinua tänä vuonna?",
  344: "Miten olet muuttunut?",
  345: "Mikä unelma jäi toteutumatta?",
  346: "Millaista hyvää tapahtui?",
  347: "Mistä virheestä opit tänä vuonna?",
  348: "Mikä suhde syveni?",
  349: "Millainen tavoite saavutettiin?",
  350: "Mistä on vaikea hyvästellä tämä vuosi?",
  351: "Mikä tekee sinusta kiitollisen juuri nyt?",
  352: "Millainen haluaisit olla ensi vuonna?",
  353: "Mikä unelma odottaa toteutumista?",
  354: "Miten haluat kasvaa ensi vuonna?",
  355: "Mikä on tärkeä tavoitteesi?",
  356: "Millaista rakkautta haluat kokea?",
  357: "Mistä haluat oppia enemmän?",
  358: "Mikä seikkailu odottaa sinua?",
  359: "Millainen muutos on edessä?",
  360: "Mitä lupaat itsellesi ensi vuodelle?",
  361: "Mikä tästä vuodesta ansaitsee tulla muistelluksi vielä vuosien päästä?",
  362: "Mistä olet kiitollinen itsessäsi juuri nyt?",
  363: "Mitä haluat jättää tähän vuoteen lopullisesti?",
  364: "Mitä toivot salaa ensi vuodelta?",
  365: "Millä sanoilla kuvailisit kulunutta vuotta itsellesi?"
};
